POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvcmlzbmlrM0Brb3Jpc25pay5jb20iLCJpZCI6MywiaWF0IjoxNjUyODE5MDgyfQ.p0igZDtpG6pznzFSSq_0PI49TVpefB3oFh-yZWWxu6c

{
    "title": "Disabled...",
    "author": "Šećo",
    "url": "https://www.example.com/45",
    "likes": 12,
    "yearWritten": 2020
}