POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvcmlzbmlrQGtvcmlzbmlrLmNvbSIsImlkIjoxLCJpYXQiOjE2NTI3MzE5NDl9.izP0Xu2onPHuCxL-daMhjSQF0tp_K3DXl75Iz-bxzaw

{
    "title": "Trying with operators - react",
    "author": "Šećo",
    "url": "https://www.example.com/45",
    "likes": 12,
    "yearWritten": 2022
}